library(dplyr)
library(readr)
library(janitor)
library(tidyr)
setwd("C:/Users/alvar/OneDrive/Escritorio/DATA/Data")
#Part 1
##Ex. 1
bar_madrid <- read_delim("data_ex1.csv", delim = "@")
##Ex. 2
dim(bar_madrid)
##Ex. 3

glimpse(bar_madrid)
### The type of all of them is numeric 
### Integer should be the class of those 4 colums. We could change it 
### using the funtion class(as.integer(x)).
#Ex. 4
class(bar_madrid$Cod_Postal)
## Cod_postal is expected to be integer. However it's a
## logical one because we don't have information about this column so R code
## interpretates "NA" as a logical funtion.
#Ex. 5
class(bar_madrid$hora_ini_VS_es)
class(bar_madrid$hora_fin_LJ_es)
## It should be the same type as Hora_ini_LJ_es and Hora_fin_LJ_es (difftime), 
## but R cannot read hours with a separation between (".").
#Ex.6
## With this function I check that the statement is wright.
bar_madrid_2 <- bar_madrid %>% 
  filter(DESC_NOMBRE == 'PUERTA DEL SOL') %>%
  select(DESC_NOMBRE, lat, long)

## The problem is that the column is too narrow so R cannot read this number,
## so I will use this method
bar_madrid <- bar_madrid %>%
  mutate(lat = lat / 10^13) 

#Part 2
setwd("C:/Users/alvar/OneDrive/Escritorio/DATA/Data")

all_countries <- read_csv("countries_of_the_world.csv")
  
## With this function I descart those counties which dont´t fulfiell all fields

all_countries <- tidyr::drop_na(all_countries)

#Ex. 1
## The 10 most populated are 
all_countries %>%
  arrange(desc(Population)) %>% 
  select(Country, Population)

#Ex. 2
## This column could be generated by using mutate 
all_countries <- all_countries %>% 
  mutate(absolute_gdp = `GDP ($ per capita)` * Population)

df_inventado <- all_countries %>% 
  select(Country, Population, absolute_gdp, `GDP ($ per capita)`)

#Ex. 3
Ex3 <- all_countries %>% 
  group_by(Region) %>% 
  summarise(count= n(),
            mean = mean(`GDP ($ per capita)`),
            median = median(`GDP ($ per capita)`))

write_excel_csv(Ex3, "paises.xlsx") 
